# xcodegen project file

name: ShimejiMacClassic

options:
  xcodeVersion: 1200
  groupSortPosition: top

targets:
  ShimejiMacClassic:
    platform: macOS
    type: library.dynamic
    deploymentTarget: '10.14'
    sources:
      - src
      - ../../headers/
    settings:
      HEADER_SEARCH_PATHS:
        - ${JAVA_HOME}/include
        - ${JAVA_HOME}/include/darwin
      CLANG_ENABLE_OBJC_ARC: false
      EXECUTABLE_PREFIX: lib
      SYMROOT: $(PROJECT_DIR)/build
      OBJROOT: $(PROJECT_DIR)/build