/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_group_finity_mascotnative_macclassic_MacSwingJni */

#ifndef _Included_com_group_finity_mascotnative_macclassic_MacSwingJni
#define _Included_com_group_finity_mascotnative_macclassic_MacSwingJni
#ifdef __cplusplus
extern "C" {
#endif
#undef com_group_finity_mascotnative_macclassic_MacSwingJni_NSStatusWindowLevel
#define com_group_finity_mascotnative_macclassic_MacSwingJni_NSStatusWindowLevel 25L
/*
 * Class:     com_group_finity_mascotnative_macclassic_MacSwingJni
 * Method:    nativeSetNSWindowLevel
 * Signature: (Ljava/awt/Window;I)V
 */
JNIEXPORT void JNICALL Java_com_group_1finity_mascotnative_macclassic_MacSwingJni_nativeSetNSWindowLevel
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
